[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "data-cleaning"
version = "0.1.0"
description = "Internship Task 01 - Data Cleaning and Preprocessing"